require("remap")
require("set")
require("plugins.lazy")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.fugitive")
require("plugins.lsp_zero")
require("plugins.nvim_cmp")
require("plugins.nvimtree")
require("plugins.obsidian")
require("plugins.misc")
require("plugins.lualine")

require("misc")
require("mason").setup()
vim.cmd('colorscheme jellybeans-nvim')
